# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

os: linux
language: generic # optional, just removes the language badge

services:
  - docker

notifications:
  slack:
    secure: v5g/n5FRg5QKLfnt47wqQbOF0Uo0ZJ3PtGmOnFW7gdaBUTL5nZAOrb/tnpQzR9LqKj6YK1z4iq2PndZViWie440hyK8Jf3jEHFsiFHCC+Jwnpr+1Mg0/dndDXlcBUJr92WfkyvnECDImLl6xR/7tZUCSvXE2l+4Pno/zjYnc66NUUxxL5O9BcDl2vzHJXVJNmqePNzH7MrOlgVryhJ6g0BQLQltCBggJ0M1L9li1b7AyUWm82MvFoRDhh6xGmU7bs6j3naTkbrpPzH91Z7oHdT1ZoCxgT8i72IRPIH/RX42aszzWhBBbABBZDUWR7KtSNCySFw+eN4HdNDfZc6Ng+33GlOA7ZShIbp8NqLK7poTexo+FnlYOsRhbNkQBoI34bUz0C0pJ/TbWUqjp2CMfgFSIhylGe/Gttq19eHYSjPNZ7EH0mwGlLOdOcvr/DQZnTEb7H9lbbMjefxvAGgJGvsYMvRTK3gAiOKl1MwrVxaWoDGmSjTteSl61jXr6N+12lfCwh+tvUNSEctwslXU2dIJ/UttNyOthNak5k2tsvVmiiDnuoSZrellnmbRHNlB9paUOWyPjTofGkfkRqN8m2U85I8ruvzd6X2uMjG8gYwuSPaKyleim3qSueGxYC6uG17bdF7oaxzrRkI8GOpbbJSetZBkmUpqhm+c0q4E0csI=
  email: false

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global:
    - ROS_REPO=ros
    - ADDITIONAL_DEBS='python-lxml python-pyqtgraph'
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - BUILDER=colcon
    - CATKIN_LINT=pedantic
    # DEBIAN_FRONTEND disables interactive frontends when installing packages. This is necessary for tzdata.
    - DOCKER_RUN_OPTS='-e DEBIAN_FRONTEND=noninteractive'
    - DOWNSTREAM_WORKSPACE=.rosinstall
    - AFTER_INSTALL_TARGET_DEPENDENCIES='pip install monotonic && pip install odrive'

jobs:
  include:
    - name: "Melodic"
      env: ROS_DISTRO=melodic
    - name: "clang-format"
      env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file
    - name: "flake8"
      language: python
      python: 3.7
      install:
        - pip install flake8 pep8-naming flake8-blind-except flake8-string-format flake8-builtins flake8-commas flake8-quotes flake8-print flake8-docstrings flake8-import-order flake8-colors
      script: flake8

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
