# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

language: generic # optional, just removes the language badge

services:
  - docker

notifications:
  slack:
    secure: chFpoojxMi0Jq4o3oDGRYsEjGE2D2/UB2lj2xTc+lQpg+68gFjuwBqek0jGOT/opqyMxHOEuL3Ok3hpo5gIyYVpwURMOkxIVuZzbHkvALdbwUNfETR4/CyQthgYSSvCBNVL2wf33Z2cEAKTlC2cq3hc5k76fDAtsdSi195oPA9oDlEcA5ce8l9XKoi5CN2i7Ug2aIQpHNnQHykvdQdu9vn5Nz8IrGwNcmzNpBPCVcKliZAOkCuhiYCEV89JTz5emyDTMaKPj8UrlgUs2supNX/UejdjSWvQ2ab2rhdF3Npc+l1hhzt2/3IQ8zut9KFJdWIHK0qx8KSQWhgRtilVwp5rCkx5F9gCPPxjZzVkRoFzPn9aK3jHhewHVb2YGJvWs+b+wfl9n/b6qVtz/lSoyuvDdvnsz2agKLK6cyfYSLfnOEyEdLDACAp+WKBUoUztkKDKnYu9KCJTZ3aIxW3SfecqyggwxAnDaX+ott7jHNoueuiGXennMCyYGDMHm4eS9G0S/co1jvPZnE4veu+kBYJtYP+X8z4py0h2/MBl0KUWgFSUb7zAVXDlKpogeVD0mpu0fgK/uRwN5fFVi9Ssk6YoG1raoK83Uypywe7fZdG3PM9oV3V40bF9+OPZMoNxkP0hVUxiBx0OuJApHSQEWQHOSiOQsKxiqGQKKcBF+Xik=
  email: false

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global:
    - ROS_REPO=ros
    - ADDITIONAL_DEBS='python-lxml python-pyqtgraph libusb-1.0-0-dev libjsoncpp-dev'
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
    - BUILDER=colcon
    - CATKIN_LINT=pedantic
    - CATKIN_LINT_ARGS='--ignore launch_depend'
    # DEBIAN_FRONTEND disables interactive frontends when installing packages. This is necessary for tzdata.
    - DOCKER_RUN_OPTS='-e DEBIAN_FRONTEND=noninteractive'
    - DOWNSTREAM_WORKSPACE=.rosinstall
    - AFTER_INSTALL_TARGET_DEPENDENCIES='pip install monotonic && pip install odrive'

jobs:
  include:
    - name: "Melodic"
      env: ROS_DISTRO=melodic
    - name: "clang-format"
      env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file
    - name: "flake8"
      language: python
      python: 3.7
      install:
        - pip install flake8 pep8-naming flake8-blind-except flake8-string-format flake8-builtins flake8-commas flake8-quotes flake8-print flake8-docstrings flake8-import-order flake8-colors
      script: flake8

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
